export { default as Education } from './education'
export { default as Intro } from './intro'
export { default as Jobs } from './jobs'
export { default as Projects } from './projects'
export { default as Resume } from './resume'