export const webPortfolio = [
    { 
        key: "sticky",
        name: "Stic.ky",
        link: "http://stic.ky",
        github: null,
        picture: null,
    },
    { 
        key: "LPG",
        name: "License Plate Game",
        link: "https://mkerbleski.github.io/License-Plate-Game/",
        github: "https://github.com/MKerbleski/License-Plate-Game",        
        picture: null,
    },
    { 
        key: "mud",
        name: "MUD",
        link: "https://amudappthatdoesntsuck.xyz/game",
        github: "https://github.com/MKerbleski/LambdaMUD-Client",
        picture: null,
    },
    { 
        key: "gameOfLife",
        name: "Cellular Automata",
        link: "https://mkerbleski.github.io/Conways-Life/",
        github: "https://github.com/MKerbleski/Conways-Life",
        picture: null,
    },
    { 
        key: "frontEnd",
        name: "S&J Architecture",
        link: "https://mkerbleski.github.io/User-Interface-Project-Week/",
        github: "https://github.com/MKerbleski/User-Interface-Project-Week",
        picture: null,
    },
    { 
        key: "frontEnd",
        name: "Portfolio",
        link: "https://mikerble.ski",
        github: "https://github.com/MKerbleski/Portfolio",
        picture: null,
    },
    { 
        key: "hackaathon",
        name: "Job Trends",
        link: "https://jobtrends.site/",
        github: "https://github.com/MKerbleski/Hackathon-July2018",
        picture: null,
    },
]